### ISSUE TITLE
Password length limitation

### ISSUE THREAD

**Issue by gtellalov** [k9mail/k9mail.app#231]
I have an account with a password that is 26 characters long, but when entering it, one character gets cut off.

Can you please remove the password length limitation?

**Comment by AnXh3L0** [comment]
Hi @gtellalov, please not that this is not the bug tracker for the K9 Mail/Thunderbird Mobile app, but for the website itself. Please check the following issue tracker: https://github.com/thunderbird/thunderbird-android/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen and see if your issue is already there, and how to address it. Thanks!
